-- ATIVIDADE 06 - SISTEMA DE CURSOS ONLINE (EAD)

-- CRIAR O BANCO DE DADOS
CREATE DATABASE DB_CURSO_DA_MINHA_VIDA;

-- SELECIONAR O BANCO DE DADOS
USE DB_CURSO_DA_MINHA_VIDA;

-- CRIAR A TABELA TB_CATEGORIAS
CREATE TABLE TB_CATEGORIAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- CRIAR A TABELA TB_CURSOS
CREATE TABLE TB_CURSOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    CARGA_HORARIA INT NOT NULL,
    NIVEL VARCHAR(30) NOT NULL,
    CATEGORIA_ID BIGINT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS(ID)
);

-- INSERIR 5 REGISTROS NA TABELA TB_CATEGORIAS
INSERT INTO TB_CATEGORIAS (TIPO, DESCRICAO) VALUES
('PROGRAMAÇÃO', 'CURSOS DE DESENVOLVIMENTO DE SOFTWARE'),
('DESIGN', 'CURSOS DE DESIGN GRÁFICO E UX/UI'),
('NEGÓCIOS', 'CURSOS DE ADMINISTRAÇÃO E GESTÃO'),
('MARKETING', 'CURSOS DE MARKETING DIGITAL'),
('IDIOMAS', 'CURSOS DE LÍNGUAS ESTRANGEIRAS');

-- INSERIR 8 REGISTROS NA TABELA TB_CURSOS
INSERT INTO TB_CURSOS (NOME, VALOR, CARGA_HORARIA, NIVEL, CATEGORIA_ID) VALUES
('JAVA COMPLETO', 850.00, 120, 'INTERMEDIÁRIO', 1),
('PYTHON PARA INICIANTES', 450.00, 60, 'BÁSICO', 1),
('JAVASCRIPT AVANÇADO', 920.00, 100, 'AVANÇADO', 1),
('DESIGN UX/UI', 780.00, 80, 'INTERMEDIÁRIO', 2),
('PHOTOSHOP PROFISSIONAL', 520.00, 50, 'INTERMEDIÁRIO', 2),
('GESTÃO DE PROJETOS', 1200.00, 150, 'AVANÇADO', 3),
('MARKETING DIGITAL', 680.00, 90, 'INTERMEDIÁRIO', 4),
('INGLÊS AVANÇADO', 890.00, 200, 'AVANÇADO', 5);

-- SELECT DE CURSOS COM VALOR MAIOR QUE R$ 500,00
SELECT * FROM TB_CURSOS WHERE VALOR > 500.00;

-- SELECT DE CURSOS COM VALOR ENTRE R$ 600,00 E R$ 1000,00
SELECT * FROM TB_CURSOS WHERE VALOR BETWEEN 600.00 AND 1000.00;

-- SELECT DE CURSOS QUE POSSUEM A LETRA J NO NOME
SELECT * FROM TB_CURSOS WHERE NOME LIKE '%J%';

-- SELECT COM INNER JOIN UNINDO TB_CURSOS E TB_CATEGORIAS
SELECT 
    TB_CURSOS.ID,
    TB_CURSOS.NOME,
    TB_CURSOS.VALOR,
    TB_CURSOS.CARGA_HORARIA,
    TB_CURSOS.NIVEL,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_CURSOS
INNER JOIN TB_CATEGORIAS ON TB_CURSOS.CATEGORIA_ID = TB_CATEGORIAS.ID;

-- SELECT COM INNER JOIN FILTRANDO POR UMA CATEGORIA ESPECÍFICA (PROGRAMAÇÃO - JAVA)
SELECT 
    TB_CURSOS.ID,
    TB_CURSOS.NOME,
    TB_CURSOS.VALOR,
    TB_CURSOS.CARGA_HORARIA,
    TB_CURSOS.NIVEL,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_CURSOS
INNER JOIN TB_CATEGORIAS ON TB_CURSOS.CATEGORIA_ID = TB_CATEGORIAS.ID
WHERE TB_CATEGORIAS.TIPO = 'PROGRAMAÇÃO' AND TB_CURSOS.NOME LIKE '%JAVA%';