-- ATIVIDADE 05 - SISTEMA DE MATERIAL DE CONSTRUÇÃO

-- CRIAR O BANCO DE DADOS
CREATE DATABASE DB_CONSTRUINDO_VIDAS;

-- SELECIONAR O BANCO DE DADOS
USE DB_CONSTRUINDO_VIDAS;

-- CRIAR A TABELA TB_CATEGORIAS
CREATE TABLE TB_CATEGORIAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- CRIAR A TABELA TB_PRODUTOS
CREATE TABLE TB_PRODUTOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    UNIDADE_MEDIDA VARCHAR(20) NOT NULL,
    CATEGORIA_ID BIGINT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS(ID)
);

-- INSERIR 5 REGISTROS NA TABELA TB_CATEGORIAS
INSERT INTO TB_CATEGORIAS (TIPO, DESCRICAO) VALUES
('HIDRÁULICA', 'MATERIAIS PARA INSTALAÇÕES HIDRÁULICAS'),
('ELÉTRICA', 'MATERIAIS PARA INSTALAÇÕES ELÉTRICAS'),
('ACABAMENTO', 'MATERIAIS PARA ACABAMENTO E REVESTIMENTO'),
('ESTRUTURAL', 'MATERIAIS PARA ESTRUTURA E FUNDAÇÃO'),
('FERRAMENTAS', 'FERRAMENTAS E EQUIPAMENTOS');

-- INSERIR 8 REGISTROS NA TABELA TB_PRODUTOS
INSERT INTO TB_PRODUTOS (NOME, VALOR, QUANTIDADE_ESTOQUE, UNIDADE_MEDIDA, CATEGORIA_ID) VALUES
('CANO PVC 100MM', 45.00, 150, 'METRO', 1),
('REGISTRO DE GAVETA', 85.00, 80, 'UNIDADE', 1),
('FIO ELÉTRICO 2.5MM', 120.00, 200, 'ROLO', 2),
('DISJUNTOR 40A', 35.00, 100, 'UNIDADE', 2),
('CIMENTO PORTLAND', 32.00, 500, 'SACO 50KG', 4),
('TINTA ACRÍLICA BRANCA', 145.00, 90, 'LATA 18L', 3),
('PISO CERÂMICO', 78.00, 300, 'CAIXA', 3),
('FURADEIRA ELÉTRICA', 250.00, 25, 'UNIDADE', 5);

-- SELECT DE PRODUTOS COM VALOR MAIOR QUE R$ 100,00
SELECT * FROM TB_PRODUTOS WHERE VALOR > 100.00;

-- SELECT DE PRODUTOS COM VALOR ENTRE R$ 70,00 E R$ 150,00
SELECT * FROM TB_PRODUTOS WHERE VALOR BETWEEN 70.00 AND 150.00;

-- SELECT DE PRODUTOS QUE POSSUEM A LETRA C NO NOME
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE '%C%';

-- SELECT COM INNER JOIN UNINDO TB_PRODUTOS E TB_CATEGORIAS
SELECT 
    TB_PRODUTOS.ID,
    TB_PRODUTOS.NOME,
    TB_PRODUTOS.VALOR,
    TB_PRODUTOS.QUANTIDADE_ESTOQUE,
    TB_PRODUTOS.UNIDADE_MEDIDA,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_PRODUTOS
INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID;

-- SELECT COM INNER JOIN FILTRANDO POR UMA CATEGORIA ESPECÍFICA (HIDRÁULICA)
SELECT 
    TB_PRODUTOS.ID,
    TB_PRODUTOS.NOME,
    TB_PRODUTOS.VALOR,
    TB_PRODUTOS.QUANTIDADE_ESTOQUE,
    TB_PRODUTOS.UNIDADE_MEDIDA,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_PRODUTOS
INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID
WHERE TB_CATEGORIAS.TIPO = 'HIDRÁULICA';