-- ATIVIDADE 04 - SISTEMA DE AÇOUGUE

-- CRIAR O BANCO DE DADOS
CREATE DATABASE DB_CIDADE_DAS_CARNES;

-- SELECIONAR O BANCO DE DADOS
USE DB_CIDADE_DAS_CARNES;

-- CRIAR A TABELA TB_CATEGORIAS
CREATE TABLE TB_CATEGORIAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- CRIAR A TABELA TB_PRODUTOS
CREATE TABLE TB_PRODUTOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    PESO_KG DECIMAL(5, 2) NOT NULL,
    ORIGEM VARCHAR(50) NOT NULL,
    CATEGORIA_ID BIGINT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS(ID)
);

-- INSERIR 5 REGISTROS NA TABELA TB_CATEGORIAS
INSERT INTO TB_CATEGORIAS (TIPO, DESCRICAO) VALUES
('BOVINOS', 'CARNES DE BOI E VACA'),
('SUÍNOS', 'CARNES DE PORCO'),
('AVES', 'CARNES DE FRANGO E OUTRAS AVES'),
('EMBUTIDOS', 'LINGUIÇAS, SALSICHAS E SIMILARES'),
('CORTES NOBRES', 'CORTES ESPECIAIS E PREMIUM');

-- INSERIR 8 REGISTROS NA TABELA TB_PRODUTOS
INSERT INTO TB_PRODUTOS (NOME, VALOR, PESO_KG, ORIGEM, CATEGORIA_ID) VALUES
('PICANHA', 89.90, 1.50, 'BRASIL', 1),
('ALCATRA', 45.00, 1.00, 'BRASIL', 1),
('COSTELA SUÍNA', 35.00, 2.00, 'BRASIL', 2),
('FRANGO INTEIRO', 18.00, 2.50, 'BRASIL', 3),
('LINGUIÇA TOSCANA', 28.00, 1.00, 'BRASIL', 4),
('FILÉ MIGNON', 120.00, 1.00, 'BRASIL', 5),
('COXA E SOBRECOXA', 22.00, 1.50, 'BRASIL', 3),
('BACON DEFUMADO', 55.00, 0.80, 'BRASIL', 2);

-- SELECT DE PRODUTOS COM VALOR MAIOR QUE R$ 50,00
SELECT * FROM TB_PRODUTOS WHERE VALOR > 50.00;

-- SELECT DE PRODUTOS COM VALOR ENTRE R$ 50,00 E R$ 150,00
SELECT * FROM TB_PRODUTOS WHERE VALOR BETWEEN 50.00 AND 150.00;

-- SELECT DE PRODUTOS QUE POSSUEM A LETRA C NO NOME
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE '%C%';

-- SELECT COM INNER JOIN UNINDO TB_PRODUTOS E TB_CATEGORIAS
SELECT 
    TB_PRODUTOS.ID,
    TB_PRODUTOS.NOME,
    TB_PRODUTOS.VALOR,
    TB_PRODUTOS.PESO_KG,
    TB_PRODUTOS.ORIGEM,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_PRODUTOS
INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID;

-- SELECT COM INNER JOIN FILTRANDO POR UMA CATEGORIA ESPECÍFICA (AVES)
SELECT 
    TB_PRODUTOS.ID,
    TB_PRODUTOS.NOME,
    TB_PRODUTOS.VALOR,
    TB_PRODUTOS.PESO_KG,
    TB_PRODUTOS.ORIGEM,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_PRODUTOS
INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID
WHERE TB_CATEGORIAS.TIPO = 'AVES';