-- ATIVIDADE 03 - SISTEMA DE FARMÁCIA

-- CRIAR O BANCO DE DADOS
CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

-- SELECIONAR O BANCO DE DADOS
USE DB_FARMACIA_BEM_ESTAR;

-- CRIAR A TABELA TB_CATEGORIAS
CREATE TABLE TB_CATEGORIAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- CRIAR A TABELA TB_PRODUTOS
CREATE TABLE TB_PRODUTOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    QUANTIDADE_ESTOQUE INT NOT NULL,
    NECESSITA_RECEITA BOOLEAN NOT NULL,
    CATEGORIA_ID BIGINT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS(ID)
);

-- INSERIR 5 REGISTROS NA TABELA TB_CATEGORIAS
INSERT INTO TB_CATEGORIAS (TIPO, DESCRICAO) VALUES
('MEDICAMENTOS', 'REMÉDIOS E FÁRMACOS'),
('COSMÉTICOS', 'PRODUTOS DE BELEZA E CUIDADOS PESSOAIS'),
('HIGIENE', 'PRODUTOS DE HIGIENE PESSOAL'),
('SUPLEMENTOS', 'VITAMINAS E SUPLEMENTOS ALIMENTARES'),
('DERMOCOSMÉTICOS', 'PRODUTOS DERMATOLÓGICOS');

-- INSERIR 8 REGISTROS NA TABELA TB_PRODUTOS
INSERT INTO TB_PRODUTOS (NOME, VALOR, QUANTIDADE_ESTOQUE, NECESSITA_RECEITA, CATEGORIA_ID) VALUES
('PARACETAMOL 750MG', 12.50, 200, FALSE, 1),
('DIPIRONA 500MG', 8.90, 150, FALSE, 1),
('SHAMPOO ANTICASPA', 35.00, 80, FALSE, 2),
('SABONETE LÍQUIDO', 18.00, 120, FALSE, 3),
('VITAMINA C 1000MG', 45.00, 90, FALSE, 4),
('PROTETOR SOLAR FPS 50', 65.00, 60, FALSE, 5),
('ANTIBIÓTICO AMOXICILINA', 55.00, 50, TRUE, 1),
('CREME ANTI-IDADE', 89.00, 40, FALSE, 2);

-- SELECT DE PRODUTOS COM VALOR MAIOR QUE R$ 50,00
SELECT * FROM TB_PRODUTOS WHERE VALOR > 50.00;

-- SELECT DE PRODUTOS COM VALOR ENTRE R$ 5,00 E R$ 60,00
SELECT * FROM TB_PRODUTOS WHERE VALOR BETWEEN 5.00 AND 60.00;

-- SELECT DE PRODUTOS QUE POSSUEM A LETRA C NO NOME
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE '%C%';

-- SELECT COM INNER JOIN UNINDO TB_PRODUTOS E TB_CATEGORIAS
SELECT 
    TB_PRODUTOS.ID,
    TB_PRODUTOS.NOME,
    TB_PRODUTOS.VALOR,
    TB_PRODUTOS.QUANTIDADE_ESTOQUE,
    TB_PRODUTOS.NECESSITA_RECEITA,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_PRODUTOS
INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID;

-- SELECT COM INNER JOIN FILTRANDO POR UMA CATEGORIA ESPECÍFICA (COSMÉTICOS)
SELECT 
    TB_PRODUTOS.ID,
    TB_PRODUTOS.NOME,
    TB_PRODUTOS.VALOR,
    TB_PRODUTOS.QUANTIDADE_ESTOQUE,
    TB_PRODUTOS.NECESSITA_RECEITA,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_PRODUTOS
INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID
WHERE TB_CATEGORIAS.TIPO = 'COSMÉTICOS';