-- ATIVIDADE 01 - SISTEMA DE GAME ONLINE

-- CRIAR O BANCO DE DADOS
CREATE DATABASE DB_GENERATION_GAME_ONLINE;

-- SELECIONAR O BANCO DE DADOS
USE DB_GENERATION_GAME_ONLINE;

-- CRIAR A TABELA TB_CLASSES
CREATE TABLE TB_CLASSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- CRIAR A TABELA TB_PERSONAGENS
CREATE TABLE TB_PERSONAGENS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    PODER_ATAQUE INT NOT NULL,
    PODER_DEFESA INT NOT NULL,
    NIVEL INT NOT NULL,
    CLASSE_ID BIGINT,
    FOREIGN KEY (CLASSE_ID) REFERENCES TB_CLASSES(ID)
);

-- INSERIR 5 REGISTROS NA TABELA TB_CLASSES
INSERT INTO TB_CLASSES (NOME, DESCRICAO) VALUES
('GUERREIRO', 'CLASSE COM ALTO PODER DE ATAQUE CORPO A CORPO'),
('MAGO', 'CLASSE COM PODERES MÁGICOS E FEITIÇOS'),
('ARQUEIRO', 'CLASSE COM HABILIDADES DE ATAQUE A DISTÂNCIA'),
('PALADINO', 'CLASSE COM EQUILÍBRIO ENTRE ATAQUE E CURA'),
('ASSASSINO', 'CLASSE ÁGIL COM ATAQUES CRÍTICOS');

-- INSERIR 8 REGISTROS NA TABELA TB_PERSONAGENS
INSERT INTO TB_PERSONAGENS (NOME, PODER_ATAQUE, PODER_DEFESA, NIVEL, CLASSE_ID) VALUES
('THOR', 2500, 1800, 50, 1),
('GANDALF', 3000, 1200, 60, 2),
('LEGOLAS', 2200, 1500, 45, 3),
('ARTHUR', 1800, 2100, 40, 4),
('EZIO', 2800, 1000, 55, 5),
('CONAN', 3500, 1600, 65, 1),
('MERLIN', 1900, 900, 35, 2),
('KATNISS', 1500, 1300, 30, 3);

-- SELECT DE PERSONAGENS COM PODER DE ATAQUE MAIOR QUE 2000
SELECT * FROM TB_PERSONAGENS WHERE PODER_ATAQUE > 2000;

-- SELECT DE PERSONAGENS COM PODER DE DEFESA ENTRE 1000 E 2000
SELECT * FROM TB_PERSONAGENS WHERE PODER_DEFESA BETWEEN 1000 AND 2000;

-- SELECT DE PERSONAGENS QUE POSSUEM A LETRA C NO NOME
SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE '%C%';

-- SELECT COM INNER JOIN UNINDO TB_PERSONAGENS E TB_CLASSES
SELECT 
    TB_PERSONAGENS.ID,
    TB_PERSONAGENS.NOME,
    TB_PERSONAGENS.PODER_ATAQUE,
    TB_PERSONAGENS.PODER_DEFESA,
    TB_PERSONAGENS.NIVEL,
    TB_CLASSES.NOME AS CLASSE
FROM TB_PERSONAGENS
INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSE_ID = TB_CLASSES.ID;

-- SELECT COM INNER JOIN FILTRANDO POR UMA CLASSE ESPECÍFICA (ARQUEIRO)
SELECT 
    TB_PERSONAGENS.ID,
    TB_PERSONAGENS.NOME,
    TB_PERSONAGENS.PODER_ATAQUE,
    TB_PERSONAGENS.PODER_DEFESA,
    TB_PERSONAGENS.NIVEL,
    TB_CLASSES.NOME AS CLASSE
FROM TB_PERSONAGENS
INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSE_ID = TB_CLASSES.ID
WHERE TB_CLASSES.NOME = 'ARQUEIRO';