-- ATIVIDADE 02 - SISTEMA DE PIZZARIA

-- CRIAR O BANCO DE DADOS
CREATE DATABASE DB_PIZZARIA_LEGAL;

-- SELECIONAR O BANCO DE DADOS
USE DB_PIZZARIA_LEGAL;

-- CRIAR A TABELA TB_CATEGORIAS
CREATE TABLE TB_CATEGORIAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- CRIAR A TABELA TB_PIZZAS
CREATE TABLE TB_PIZZAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    TAMANHO VARCHAR(20) NOT NULL,
    DISPONIVEL BOOLEAN NOT NULL,
    CATEGORIA_ID BIGINT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS(ID)
);

-- INSERIR 5 REGISTROS NA TABELA TB_CATEGORIAS
INSERT INTO TB_CATEGORIAS (TIPO, DESCRICAO) VALUES
('SALGADA TRADICIONAL', 'PIZZAS SALGADAS CLÁSSICAS'),
('SALGADA ESPECIAL', 'PIZZAS SALGADAS GOURMET'),
('DOCE', 'PIZZAS DOCES'),
('VEGANA', 'PIZZAS SEM INGREDIENTES DE ORIGEM ANIMAL'),
('PREMIUM', 'PIZZAS COM INGREDIENTES NOBRES');

-- INSERIR 8 REGISTROS NA TABELA TB_PIZZAS
INSERT INTO TB_PIZZAS (NOME, VALOR, TAMANHO, DISPONIVEL, CATEGORIA_ID) VALUES
('MARGHERITA', 42.00, 'MÉDIA', TRUE, 1),
('CALABRESA', 38.00, 'MÉDIA', TRUE, 1),
('PORTUGUESA', 48.00, 'GRANDE', TRUE, 1),
('QUATRO QUEIJOS', 55.00, 'GRANDE', TRUE, 2),
('CHOCOLATE COM MORANGO', 45.00, 'MÉDIA', TRUE, 3),
('BRIGADEIRO', 40.00, 'MÉDIA', TRUE, 3),
('VEGETARIANA', 52.00, 'GRANDE', TRUE, 4),
('SALMÃO COM ALCAPARRAS', 89.00, 'GRANDE', TRUE, 5);

-- SELECT DE PIZZAS COM VALOR MAIOR QUE R$ 45,00
SELECT * FROM TB_PIZZAS WHERE VALOR > 45.00;

-- SELECT DE PIZZAS COM VALOR ENTRE R$ 50,00 E R$ 100,00
SELECT * FROM TB_PIZZAS WHERE VALOR BETWEEN 50.00 AND 100.00;

-- SELECT DE PIZZAS QUE POSSUEM A LETRA M NO NOME
SELECT * FROM TB_PIZZAS WHERE NOME LIKE '%M%';

-- SELECT COM INNER JOIN UNINDO TB_PIZZAS E TB_CATEGORIAS
SELECT 
    TB_PIZZAS.ID,
    TB_PIZZAS.NOME,
    TB_PIZZAS.VALOR,
    TB_PIZZAS.TAMANHO,
    TB_PIZZAS.DISPONIVEL,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_PIZZAS
INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID;

-- SELECT COM INNER JOIN FILTRANDO POR UMA CATEGORIA ESPECÍFICA (DOCE)
SELECT 
    TB_PIZZAS.ID,
    TB_PIZZAS.NOME,
    TB_PIZZAS.VALOR,
    TB_PIZZAS.TAMANHO,
    TB_PIZZAS.DISPONIVEL,
    TB_CATEGORIAS.TIPO AS CATEGORIA
FROM TB_PIZZAS
INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID
WHERE TB_CATEGORIAS.TIPO = 'DOCE';