-- ATIVIDADE 02 - SISTEMA DE E-COMMERCE

-- 1. CRIAR O BANCO DE DADOS
CREATE DATABASE DB_ECOMMERCE;

-- SELECIONAR O BANCO DE DADOS
USE DB_ECOMMERCE;

-- 2. CRIAR A TABELA DE PRODUTOS
CREATE TABLE PRODUTOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    ESTOQUE INT NOT NULL,
    MARCA VARCHAR(50) NOT NULL
);

-- 3. INSERIR NO MÍNIMO 8 REGISTROS
INSERT INTO PRODUTOS (NOME, CATEGORIA, PRECO, ESTOQUE, MARCA) VALUES
('NOTEBOOK DELL INSPIRON', 'INFORMÁTICA', 2800.00, 15, 'DELL'),
('MOUSE GAMER RGB', 'INFORMÁTICA', 150.00, 50, 'LOGITECH'),
('TECLADO MECÂNICO', 'INFORMÁTICA', 350.00, 30, 'RAZER'),
('MONITOR 27 POLEGADAS', 'INFORMÁTICA', 1200.00, 20, 'LG'),
('SMARTPHONE SAMSUNG GALAXY', 'CELULARES', 1800.00, 25, 'SAMSUNG'),
('FONE DE OUVIDO BLUETOOTH', 'ÁUDIO', 250.00, 40, 'JBL'),
('SMART TV 50 POLEGADAS', 'ELETRÔNICOS', 2200.00, 12, 'SAMSUNG'),
('CADEIRA GAMER', 'MÓVEIS', 890.00, 18, 'THUNDERX3'),
('WEBCAM FULL HD', 'INFORMÁTICA', 320.00, 35, 'LOGITECH'),
('SSD 1TB', 'INFORMÁTICA', 450.00, 60, 'KINGSTON');

-- 4. SELECT DE PRODUTOS COM VALOR MAIOR QUE 500
SELECT * FROM PRODUTOS WHERE PRECO > 500;

-- 5. SELECT DE PRODUTOS COM VALOR MENOR QUE 500
SELECT * FROM PRODUTOS WHERE PRECO < 500;

-- 6. ATUALIZAR UM REGISTRO DA TABELA
UPDATE PRODUTOS 
SET PRECO = 399.00, ESTOQUE = 45 
WHERE ID = 3;